version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-golang-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d5um5s9rfs03"
s3_prefix = "sam-app-golang-example"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
